---
title: "EDS 221: Day 7 Interactive Session"
author: "Josephine Cardelle"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)

```

```{r}
penguins_sub <- penguins %>%
  filter(island == c("Biscoe", "Dream")) %>%
  select(-c(year, sex)) %>%
  mutate(body_mass_kg = body_mass_g / 1000) %>%
  rename(location = island)
```

```{r}
penguins_sub2 <- penguins %>%
  filter(species == "Adelie") %>%
 filter(!is.na(flipper_length_mm)) %>%
  group_by(sex) %>%
  summarize(flipper_length_mean = mean(flipper_length_mm), flipper_length_stdv = sd(flipper_length_mm), sample_size = n())
```

```{r}
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )

animals2 <- tibble::tribble(
     ~location,      ~full_site_name, ~jurisdiction,
       "beach",       "Goleta Beach",     "SB City",
      "lagoon",        "UCSB Lagoon",        "UCSB",
       "bluff",       "Ellwood Mesa",     "SB City",
        "oaks", "Fremont Campground",        "USFS"
     )
```

```{r}
library(tidyverse)
library(lubridate)

```

```{r}
my_date <- "03-05-1998"
lubridate::mdy(my_date)

my_date <- "11/7/2003"
lubridate::mdy(my_date)

my_date <- "08-Jun-1991"
lubridate::dmy(my_date)

my_date <- "19960518"
my_date <- lubridate::ymd(my_date)

ymd(my_date)

lubridate::mdy("1950-08-30")
class(my_date)

```

```{r}
time <- "2020-08-12 11:18"
time <- ymd_hm(time)

with_tz(time, "America/Los_Angeles")
with_tz(time, "Australia/Sydney")

my_time <- lubridate::ymd_hms(time)
week(my_time)
hour(my_time)
day(my_time)

```

```{r}
comp_time_start <- Sys.time()
comp_time_end <- Sys.time()

comp_time_end - comp_time_start
```

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_counts <- urchin_counts %>%
  mutate(date = lubridate::mdy(date)) %>%
  mutate(year = year(date),
         month = month(date),
         day = day(date))

urchin_counts %>%
  group_by(year) %>%
  summarise(total = n())
```

```{r}
day_1 <- ymd("2020-01-06")
day_2 <- ymd("2020-05-18")
day_3 <- ymd("2024-08-19")

time_interval <- interval(day_1, day_2)
time_length(time_interval, "week")

time_length(interval(day_2, day_3), "year")
```

```{r}
my_string <- "Teddy loves eating salmon and socks."

# Does the pattern "love" exist within the string?
my_string %>% str_detect("love")

# Does the pattern "pup" exist within the string?
my_string %>% str_detect("pup")

my_string <- c("burrito", "fish taco", "Taco salad")

# Does the vector element contain the pattern "fish"?
my_string %>% str_detect("fish")



```

```{r}
skywalkers <- starwars %>%
  filter(str_detect(name, "Skywalker"))
```

```{r}
firewalkers <- starwars %>%
  mutate(name = str_replace(name, 
                            pattern = "Sky", 
                            replacement = "Fire"))

```

```{r}
feedback <- c("I ate some nachos", "Wednesday morning    ")
str_squish(feedback)
str_trim(feedback)

str_to_lower(feedback)
str_to_upper(feedback)
str_to_title(feedback)

str_count(feedback, pattern = "nachos")
```

